baseurl: /neo4j-flask
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
title: neo4j-flask
description: A microblog application powered by Flask and Neo4j.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman